[package]
name = "rrdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.10.0"
serde = { version = "1.0.196", features = ["derive"] }
sqlparser = "0.43.1"
